# Generated by Django 4.0.7 on 2023-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
