# Generated by Django 4.0.7 on 2023-03-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_image_ad_picture_ad_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
